name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build"
          target: "/home/ec2-user/react-app"

      # - name: SSH into EC2 & Deploy App
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ec2-user
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
            # sudo yum install -y nginx
            # sudo systemctl start nginx
            # sudo systemctl enable nginx
            # sudo rm -rf /usr/share/nginx/html/*
            # sudo cp -r /home/ec2-user/react-app/build/* /usr/share/nginx/html/
            # sudo systemctl restart nginx
